#!/bin/sh
# generates a self signed certificate and key
# this certificate will not be accepted by flash movies
# and is intendet to be used for testing the policy server.
#
# copy your valid certificate and secret key to 
# ./ssl/host.cert and ./ssl/host.key.
#
# see http://www.akadia.com/services/ssh_test_certificate.html

# Generate a Private Key
openssl genrsa -des3 -out server.key 1024
# Generate a CSR (Certificate Signing Request)
echo "Enter your domain or 'localhost' when asked for the 'Common Name' field."
openssl req -new -key server.key -out server.csr
# Remove Passphrase from Key
openssl rsa -in server.key -out host.key
# Generating a Self-Signed Certificate
openssl x509 -req -days 365 -in server.csr -signkey host.key -out host.cert && rm server.key && rm server.csr
